services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
      - deno-cache:/deno-dir/deps
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=dummyPass
      - MONGO_INITDB_DATABASE=streamSync
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--requirepass", "dummyPass", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  mongodata:
  deno-cache:
  redisdata:
